[[redirects]]
  from = "/api-proxy/*"
  to = "https://palenquego.com/api/v1/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/media-proxy/*"
  to = "https://palenquego.com/media/:splat"
  status = 200
  force = true